### ISSUE TITLE
Memory Use

### ISSUE THREAD

**Issue by guillochon** [jparrent/WISeWEBSpider#9]
Attempting to run a full rebuild on the OSC server, which has a rather modest memory budget. I'm seeing "Killed" errors, which generally suggest that the script is running out of memory. The process is killed after about an hour of running, so unfortunately a full rebuild is requiring multiple restarts (lucky, lists.json prevents it from re-scraping the first events listed repeatedly).

My guess is there's some variable that's growing continuously as the script runs that just needs to be purged between files. It's also possible it's related to a memory leak in RoboBrowser of some sort.

**Comment by jparrent** [comment]
@guillochon I think it was last month that I started looking for that memory leak but got sidetracked. My best guess is that it has to do with the line(s) with deepcopy, but don't quote me on that. But yeah when I scrape from scratch, my computer gets a work out. I started building the scraper on a mac with 4GB of RAM and quickly migrated to the other with 16GB for this reason -- and also creating lists.json. 

I would still like to find this memory leak and plug it (through pympler or gc), but in the meantime, if you would just like to outsource full rebuilds of WISeREP to me, let me know and I can do that anytime.

**Comment by hezronobuchele** [comment]
I had similar memory issues using RoboBrowser and thanks to landing on this issue I actually figured out what the cause is. Looking at the code in this repo, RoboBrowser is initialized using `history=True` even though it's not needed as was my case. I simply set `history=False` to fix it.

**Comment by jparrent** [comment]
@hezbucho Thank you! I am hoping to refactor and clean up the spider at some point.
